telegram:
  bot:
    name: "MoodBot"
    token: "8096440732:AAEPRlC7lJ11-llgi_6GQz3sh_t5J2Od1rk"

remind:
  period: 10000

spring:
  profiles:
    active: test

  datasource:
    url: "jdbc:h2:file:./moodbot"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
